spring : 
        datasource : 
          generate-unique-name : false
        h2 : 
            console : 
                    enabled : true
                    
        jpa :
         properties :
           javax : 
              persistence : 
                validation : 
                  mode : none  